mod common;
use std::{fs, process::Command};

#[test]
fn authored_line_arrays_preserve_integer_values_and_original_material_bytes() {
    // SPEC-BLT-005: the actual tag parser delivers arrays to include unchanged.
    let root = tempfile::tempdir().unwrap();
    fs::write(
        root.path().join("guide.md"),
        "{% include 'notes.txt' lines=[1e0,2.0] %}\n{% include 'notes.txt' lines='1-2' %}\n",
    )
    .unwrap();
    fs::write(root.path().join("notes.txt"), "First\r\n末尾").unwrap();
    let output = Command::new(env!("CARGO_BIN_EXE_source-down"))
        .args(["render", "guide.md", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let page = fs::read_to_string(root.path().join(".source-down/pages/guide.md.md")).unwrap();
    assert_eq!(page.matches("First\r\n末尾\n\n").count(), 2);
    assert_eq!(
        page.matches("[`notes.txt:L1-L2`](../../notes.txt#L1) · bytes [0,13)")
            .count(),
        2
    );
}

#[test]
fn markdown_is_an_authored_page_with_exact_original_locations() {
    // SPEC-REN-014: this expected page is handwritten, not generated by the renderer.
    let root = tempfile::tempdir().unwrap();
    fs::write(
        root.path().join("guide.md"),
        "# Guide\n\n{% include \"snippet.rs\" id=\"f\" %}\n",
    )
    .unwrap();
    fs::write(root.path().join("snippet.rs"), "fn f() {}\n").unwrap();
    let output = Command::new(env!("CARGO_BIN_EXE_source-down"))
        .args(["render", "guide.md", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let page = fs::read_to_string(root.path().join(".source-down/pages/guide.md.md")).unwrap();
    assert_eq!(
        page,
        format!("{}\n\n", include_str!("fixtures/narrative.expected"))
    );
}

#[test]
fn markdown_context_mixed_inputs_and_empty_plugins_share_the_real_batch() {
    // SPEC-REN-014, SPEC-PLG-003, SPEC-PLG-005, SPEC-CLI-007.
    let root = tempfile::tempdir().unwrap();
    fs::create_dir(root.path().join("book")).unwrap();
    let authored = concat!(
        "# 叙述\n\n```text\n{% hidden %}\n```\n\n",
        "    {% hidden %}\n\n- item\n  {% hidden %}\n\n",
        "> {% hidden %}\n\n<div>\n{% hidden %}\n</div>\n\n",
        "`{% hidden %}`\n\n{% include 'book/a.rs' id=['f'] %}\n",
    )
    .replace("id=['f']", "id=[\"f\"]")
    .replace('\n', "\r\n");
    let authored = format!("{authored}{{% note id=[\"章节\",0] %}}\r\nEnd without newline");
    fs::write(root.path().join("book/a.md"), &authored).unwrap();
    fs::write(root.path().join("book/a.rs"), "fn f() {}\n").unwrap();
    fs::write(
        root.path().join("book/a.rs.md"),
        "# Separate authored page\n",
    )
    .unwrap();
    fs::write(root.path().join("book/empty.md"), "").unwrap();
    fs::write(root.path().join("book/skip.md"), "{% invalid %}").unwrap();
    fs::write(
        root.path().join("source-down.toml"),
        r#"config_version = 1
[inputs]
exclude = ["book/skip.md"]
[plugins.note]
command = ["python3", "note.py"]
directives = ["note"]
[plugins.observer]
command = ["python3", "observer.py"]
"#,
    )
    .unwrap();
    let inventory =
        "assert b['input_files'] == ['book/a.md','book/a.rs','book/a.rs.md','book/empty.md']\n";
    fs::write(root.path().join("note.py"), common::plugin(&format!(r#"{inventory}
assert len(b['requests']) == 1
r = b['requests'][0]
assert r['arguments']['named']['id'] == ['章节', 0]
assert r['source']['path'] == 'book/a.md'
data = open('book/a.md','rb').read()
assert data[r['source']['start_byte']:r['source']['end_byte']].decode() == '{{% note id=["章节",0] %}}'
emit({{'type':'result','batch_id':b['batch_id'],'results':[{{'id':r['id'],'status':'ok','markdown':'{{% final.literal %}}','sources':[r['source']]}}],
      'append':[],'reports':{{}},'diagnostics':[],'dependencies':[]}})
"#))).unwrap();
    fs::write(root.path().join("observer.py"), common::plugin(&format!(r#"{inventory}
assert b['requests'] == []
emit({{'type':'result','batch_id':b['batch_id'],'results':[],
      'append':[{{'page':'book/a.rs.md','markdown':'Authored appendix.','sources':[{{'path':'book/a.rs','start_byte':0,'end_byte':10,'start_line':1,'end_line':1}}]}}],
      'reports':{{'inputs':{{'markdown':'Four inputs received','sources':[]}}}},'diagnostics':[],'dependencies':[]}})
"#))).unwrap();
    for output_dir in [".source-down", "custom/nested"] {
        let output = Command::new(env!("CARGO_BIN_EXE_source-down"))
            .args(["render", "book", "--output-dir", output_dir, "--root"])
            .arg(root.path())
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        let pages = root.path().join(output_dir).join("pages/book");
        let page = fs::read_to_string(pages.join("a.md.md")).unwrap();
        assert!(page.contains("# 叙述\r\n"));
        assert_eq!(page.matches("{% hidden %}").count(), 6);
        assert!(page.contains("{% final.literal %}"));
        assert!(page.contains("End without newline\n\n"));
        assert!(page.contains("```rust\nfn f() {}\n```"));
        assert!(pages.join("a.rs.md").is_file());
        let appended = fs::read_to_string(pages.join("a.rs.md.md")).unwrap();
        assert!(appended.contains("# Separate authored page\n"));
        assert_eq!(appended.matches("# Appendix\n\n").count(), 1);
        let (_, appendix) = appended.split_once("# Appendix\n\n").unwrap();
        assert!(appendix.contains("> **Plugin**: `observer`"));
        let relative_root = if output_dir == ".source-down" {
            "../../.."
        } else {
            "../../../.."
        };
        assert!(appendix.contains(&format!(
            "[`book/a.rs:L1-L1`]({relative_root}/book/a.rs#L1)"
        )));
        assert!(appendix.ends_with("Authored appendix.\n\n"));
        assert_eq!(fs::read(pages.join("empty.md.md")).unwrap(), b"");
        assert!(!pages.join("skip.md.md").exists());
        assert!(
            root.path()
                .join(output_dir)
                .join("reports/observer/inputs.md")
                .is_file()
        );
    }
}

#[test]
fn project_code_name_is_free_while_override_requires_a_current_builtin() {
    // SPEC-BLT-001, SPEC-CLI-003: the registry owns override meaning.
    let root = tempfile::tempdir().unwrap();
    fs::write(root.path().join("guide.md"), "{% code %}\n").unwrap();
    let render = || {
        Command::new(env!("CARGO_BIN_EXE_source-down"))
            .args(["render", "guide.md", "--root"])
            .arg(root.path())
            .output()
            .unwrap()
    };
    let absent = render();
    assert_eq!(absent.status.code(), Some(1));
    assert!(String::from_utf8_lossy(&absent.stderr).contains("unregistered directive code"));
    fs::write(root.path().join("plugin.py"), common::plugin(r#"
emit({'type':'result','batch_id':b['batch_id'],'results':[{'id':r['id'],'status':'ok','markdown':'Custom code owner','sources':[r['source']]} for r in b['requests']],
      'append':[],'reports':{},'diagnostics':[],'dependencies':[]})
"#)).unwrap();
    let config = "config_version = 1\n[plugins.custom]\ncommand = ['python3','plugin.py']\ndirectives = ['code']\n";
    fs::write(root.path().join("source-down.toml"), config).unwrap();
    let custom = render();
    assert!(
        custom.status.success(),
        "{}",
        String::from_utf8_lossy(&custom.stderr)
    );
    fs::write(
        root.path().join("source-down.toml"),
        format!("{config}override = ['code']\n"),
    )
    .unwrap();
    let invalid = render();
    assert_eq!(invalid.status.code(), Some(2));
    assert!(String::from_utf8_lossy(&invalid.stderr).contains("override"));
}

#[test]
fn arrays_reach_real_external_plugins_as_structured_data() {
    // SPEC-DIR-003, SPEC-DIR-006, SPEC-PLG-005: public CLI and actual wire boundary.
    let root = tempfile::tempdir().unwrap();
    fs::write(
        root.path().join("input.rs"),
        concat!(
            "// {% note id=[\"章节\",0,{\"nested\":[true,null,\"%} [\\\" `\"]}] %}\r\n",
            "// {% note id=[] %}\n",
        ),
    )
    .unwrap();
    fs::write(
        root.path().join("source-down.toml"),
        r#"config_version = 1
[plugins.note]
command = ["python3", "plugin.py"]
directives = ["note"]
"#,
    )
    .unwrap();
    fs::write(root.path().join("plugin.py"), common::plugin(r#"
assert b['input_files'] == ['input.rs']
assert b['requests'][0]['arguments']['named']['id'] == ['章节', 0, {'nested': [True, None, '%} [" `']}]
assert b['requests'][1]['arguments']['named']['id'] == []
emit({'type':'result','batch_id':b['batch_id'],
      'results':[{'id':r['id'],'status':'ok','markdown':'array received','sources':[r['source']]} for r in b['requests']],
      'append':[],'reports':{},'diagnostics':[],'dependencies':[]})
"#)).unwrap();
    let output = Command::new(env!("CARGO_BIN_EXE_source-down"))
        .args(["render", "input.rs", "--root"])
        .arg(root.path())
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let page = fs::read_to_string(root.path().join(".source-down/pages/input.rs.md")).unwrap();
    assert_eq!(page.matches("array received").count(), 2);
}
